import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "react-toastify/dist/ReactToastify.css"; // Import CSS Toastify
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import ClientScript from "@/components/ClientScript";
import { Providers } from "@/redux/Providers";
import { ToastContainer } from "react-toastify"; // Import ToastContainer
export const metadata: Metadata = {
  title: "Create Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* Bổ sung suppressHydrationWarning vào body */}
      <body className="d-flex flex-column vh-100" suppressHydrationWarning>
        <Providers>
          <Navbar />
          <main className="flex-grow-1">{children}</main>
          <Footer />
          <ClientScript />
          <ToastContainer
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
        </Providers>
      </body>
    </html>
  );
}