import Footer from "@/components/Footer/Footer";
import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import ClientScript from "@/components/ClientScript";
export const metadata: Metadata = {
  title: "Create Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="d-flex flex-column vh-100">
        <Navbar />
        <main className="flex-grow-1">{children}</main>
        <Footer/>
        {/* Nhắn script js của bootstrap chạy ở client */}
        <ClientScript />
      </body>
    </html>
  );
}